### ISSUE TITLE
Error creando usuario con Gmail

### ISSUE THREAD

**Issue by ServicioIT** [ernestofgonzalez/djangorocket#38]
Crear un usuario con /register/ nombre + email + password funciona y redirige al home. Pero con Google, hace el registro en la DB pero retorna el error:

InvalidRequestError at /login/google/
Request req_ioKJZx6JpG2jQz: Invalid email address:

pero si lo intentas nuevamente ahora ya no sale el error....

despues de creados los usuarios no se obtiene el boton de GOOGLE para ingresar en el LOGIN
![Screenshot 2023-06-06 at 5 11 47 PM](https://github.com/ernestofgonzalez/djangorocket/assets/102474250/66b07b17-2932-47c3-b9d2-f8b59eb2e9ae)
![Screenshot 2023-06-06 at 5 15 25 PM](https://github.com/ernestofgonzalez/djangorocket/assets/102474250/d4b35444-ff98-49fe-aade-3e9927b84d7c)
![Screenshot 2023-06-06 at 5 17 37 PM](https://github.com/ernestofgonzalez/djangorocket/assets/102474250/f8b0e9c3-749b-4e62-bd2e-ce65f58335a3)

**Comment by ernestofgonzalez** [comment]
Gracias por la descripción detallada. Hoy mismo ya no tengo tiempo, pero mañana a final de día lo arreglo.

**Comment by ServicioIT** [comment]
no hay lio, sigo viendo cositas y te cuento

**Comment by ernestofgonzalez** [comment]
Ahora ya debe funcionar correctamente, @ServicioIT
